apiVersion: v1
kind: Pod
metadata:
  name: counter
  namespace: tenant-2
spec:
  containers:
  - name: count
    image: busybox
    command: ["/bin/sh"]
    args: ['-c', 'i=0; while true; do echo "$i: $(date) at ${NAMESPACE}"; i=$((i+1)); sleep 1; done']
    resources:
      requests:
        memory: "10Mi"
        cpu: "5m"
      limits:
        memory: "10Mi"
        cpu: "5m"
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace