apiVersion: v1
kind: Secret
metadata:
  name: log-recolector-config
  namespace: tenant-2
stringData:
  promtail.yaml:  |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    client:
      url: http://loki-multi-tenant-proxy.logging.svc.cluster.local:3100/api/prom/push
      basic_auth:
        username: Tenant2
        password: 2tnaneT
    scrape_configs:
      - job_name: containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: containers
              __path__: /loki/logs/containers
        pipeline_stages:
        - regex:
            expression: '^(?P<namespace>.*)\/(?P<pod>.*)\[(?P<container>.*)\]: (?P<content>.*)'
        - labels:
            namespace:
            pod:
            container:
        - output:
            source: content
      - job_name: kail
        static_configs:
          - targets:
              - localhost
            labels:
              job: kail
              __path__: /loki/logs/kail
        pipeline_stages:
        - regex:
            expression: '^time="(?P<time>.*)" level=(?P<level>.*) msg="(?P<content>.*)" cmp=(?P<component>.*)'
        - labels:
            time:
            level:
            component:
        - timestamp:
            source: time
            format: RFC3339
        - output:
            source: content
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-recolector
  namespace: tenant-2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-recolector
  namespace: tenant-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: log-recolector
  namespace: tenant-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-recolector
  namespace: tenant-2
spec:
  selector:
    matchLabels:
      app: log-recolector
      kail.ignore: "true"
  replicas: 1
  template:
    metadata:
      labels:
        app: log-recolector
        kail.ignore: "true"
    spec:
      serviceAccount: log-recolector
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: promtail-config
        secret:
          secretName: log-recolector-config
      containers:
      - name: kail
        image: abozanich/kail:v0.15.0
        command: ["/bin/sh"]
        args: ["-c", "/kail --log-file /loki/logs/kail --log-level debug --ns ${NAMESPACE} >> /loki/logs/containers"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: shared-data
          mountPath: /loki/logs
      - name: promtail
        args:
          - -config.file=/etc/promtail/promtail.yaml
        image: grafana/promtail:v1.3.0
        volumeMounts:
        - name: shared-data
          mountPath: /loki/logs
        - name: promtail-config
          mountPath: /etc/promtail
